//
//  HSPasteboardModule.swift
//  Hammerspoon 2
//
//  Created by Chris Jones on 13/05/2026.
//

import Foundation
import JavaScriptCore
import AppKit

// MARK: - Declare our JavaScript API

/// Module for interacting with the macOS pasteboard (clipboard)
///
/// The macOS pasteboard is "rich" — a single clipboard operation can carry multiple representations
/// of the same content for different applications to consume. For example, text copied from a web
/// browser may carry plain text, HTML, and RTF representations simultaneously.
///
/// ## Basic Usage
///
/// ```js
/// // Read and write plain text
/// const text = hs.pasteboard.readString()
/// hs.pasteboard.writeString("Hello from Hammerspoon!")
///
/// // Check what types are currently on the pasteboard
/// const available = hs.pasteboard.types()
///
/// // Write multiple representations at once
/// hs.pasteboard.writeObjects({
///     "public.utf8-plain-text": "Hello",
///     "public.html": "<b>Hello</b>"
/// })
///
/// // Watch for pasteboard changes
/// const handler = (changeCount) => {
///     console.log("Pasteboard changed, count:", changeCount)
///     console.log("New text:", hs.pasteboard.readString())
/// }
/// hs.pasteboard.addWatcher(handler)
/// // Later: hs.pasteboard.removeWatcher(handler)
/// ```
///
/// ## Pasteboard Conventions (nspasteboard.org)
///
/// macOS has no built-in notification API for transient or confidential clipboard content, so a
/// community convention has emerged (see [nspasteboard.org](https://nspasteboard.org)) around four
/// `org.nspasteboard.*` UTI marker types. These markers carry no payload — their mere presence on
/// the pasteboard signals intent to other applications.
///
/// ### Standard marker UTIs
///
/// | UTI | Meaning |
/// |-----|---------|
/// | `org.nspasteboard.TransientType` | Content is temporary; it will be removed or overwritten shortly. Clipboard historians should **not** record this change. |
/// | `org.nspasteboard.ConcealedType` | Content is sensitive (e.g. a password). Historians should obfuscate it if displayed and ideally encrypt it if stored. |
/// | `org.nspasteboard.AutoGeneratedType` | Content was placed by an application without any user Copy action. Historians should generally skip recording it. |
/// | `org.nspasteboard.source` | The bundle identifier of the application that placed the content. Use an empty string when the source is unknown. |
///
/// ### Legacy proprietary markers
///
/// Several apps defined their own markers before the `org.nspasteboard.*` standard existed.
/// Clipboard historians should also honour these for compatibility:
///
/// | UTI | Application |
/// |-----|-------------|
/// | `de.petermaurer.TransientPasteboardType` | TextExpander, Butler |
/// | `com.typeit4me.clipping` | TypeIt4Me |
/// | `Pasteboard generator type` | Typinator |
/// | `com.agilebits.onepassword` | 1Password (confidential) |
/// | `com.apple.is-remote-clipboard` | macOS (remote content) |
///
/// ### For scripts that write to the pasteboard
///
/// If your script temporarily commandeers the pasteboard (e.g. to trigger a paste), add
/// `org.nspasteboard.TransientType` so clipboard historians skip the entry:
///
/// ```js
/// hs.pasteboard.writeObjects({
///     "public.utf8-plain-text": "temporary value",
///     "org.nspasteboard.TransientType": ""
/// })
/// ```
///
/// For sensitive content such as a generated password, use `org.nspasteboard.ConcealedType`:
///
/// ```js
/// hs.pasteboard.writeObjects({
///     "public.utf8-plain-text": "s3cr3t!",
///     "org.nspasteboard.ConcealedType": ""
/// })
/// ```
///
/// ### For scripts that monitor the pasteboard
///
/// If you are building a clipboard history tool with `addWatcher`, skip or obfuscate entries that
/// carry any of the marker UTIs listed above:
///
/// ```js
/// const SKIP_TYPES = [
///     "org.nspasteboard.TransientType",
///     "org.nspasteboard.AutoGeneratedType",
///     "de.petermaurer.TransientPasteboardType",
///     "com.typeit4me.clipping",
///     "Pasteboard generator type",
/// ]
/// const CONCEAL_TYPES = [
///     "org.nspasteboard.ConcealedType",
///     "com.agilebits.onepassword",
/// ]
///
/// hs.pasteboard.addWatcher((changeCount) => {
///     const types = hs.pasteboard.types()
///     if (SKIP_TYPES.some(t => types.includes(t))) return        // ignore transient
///     const conceal = CONCEAL_TYPES.some(t => types.includes(t)) // handle sensitively
///     // … record or display the pasteboard contents …
/// })
/// ```
@objc protocol HSPasteboardModuleAPI: JSExport {

    // MARK: Reading

    /// Read plain text from the pasteboard
    /// - Returns: The plain text string, or null if not available
    @objc func readString() -> String?

    /// Read HTML from the pasteboard
    /// - Returns: The HTML string, or null if not available
    @objc func readHTML() -> String?

    /// Read RTF from the pasteboard
    /// - Returns: The RTF string, or null if not available
    @objc func readRTF() -> String?

    /// Read a URL from the pasteboard
    /// - Returns: The URL as a string, or null if not available
    @objc func readURL() -> String?

    /// Read an image from the pasteboard
    /// - Returns: An HSImage, or null if not available
    @objc func readImage() -> HSImage?

    /// Read raw data for a specific UTI type, returned as a base64-encoded string.
    /// Use this for types not covered by the convenience read methods.
    /// - Parameter uti: A UTI type string (e.g. "com.adobe.pdf")
    /// - Returns: A base64-encoded string, or null if the type is not available
    @objc(readData:) func readData(_ uti: String) -> String?

    // MARK: Writing

    /// Write plain text to the pasteboard, replacing all current contents
    /// - Parameter str: The text string to write
    /// - Returns: true if the write succeeded
    @objc func writeString(_ str: String) -> Bool

    /// Write HTML to the pasteboard, replacing all current contents
    /// - Parameter html: The HTML string to write
    /// - Returns: true if the write succeeded
    @objc func writeHTML(_ html: String) -> Bool

    /// Write RTF to the pasteboard, replacing all current contents
    /// - Parameter rtf: The RTF string to write
    /// - Returns: true if the write succeeded
    @objc func writeRTF(_ rtf: String) -> Bool

    /// Write a URL to the pasteboard, replacing all current contents
    /// - Parameter url: The URL string to write
    /// - Returns: true if the write succeeded
    @objc func writeURL(_ url: String) -> Bool

    /// Write an image to the pasteboard, replacing all current contents
    /// - Parameter image: An HSImage to write
    /// - Returns: true if the write succeeded
    @objc func writeImage(_ image: HSImage) -> Bool

    /// Write raw base64-encoded data for a specific UTI type, replacing all current contents.
    /// Use this for types not covered by the convenience write methods.
    /// - Parameters:
    ///   - base64: The data encoded as a base64 string
    ///   - uti: A UTI type string (e.g. "com.adobe.pdf")
    /// - Returns: true if the write succeeded
    @objc(writeData::) func writeData(_ base64: String, _ uti: String) -> Bool

    /// Write multiple type representations to the pasteboard atomically, replacing all current contents.
    /// Keys must be UTI type strings; values must be strings. This is how you provide both a plain-text
    /// fallback and a richer representation (such as HTML) in a single clipboard operation.
    ///
    /// ```js
    /// hs.pasteboard.writeObjects({
    ///     "public.utf8-plain-text": "Hello",
    ///     "public.html":            "<b>Hello</b>"
    /// })
    /// ```
    /// - Parameter representations: A JavaScript object whose keys are UTI strings and values are strings
    /// - Returns: true if the write succeeded
    @objc func writeObjects(_ representations: JSValue) -> Bool

    // MARK: Introspection

    /// Get all UTI type strings currently on the pasteboard, across all items
    /// - Returns: An array of UTI strings (e.g. ["public.utf8-plain-text", "public.html"])
    @objc func types() -> [String]

    /// Check whether a specific UTI type is currently available on the pasteboard
    /// - Parameter uti: A UTI type string to check for
    /// - Returns: true if the type is available
    @objc func hasType(_ uti: String) -> Bool

    /// The pasteboard change count. Increments each time any application writes to the pasteboard.
    /// Comparing a saved value to the current value is the standard way to detect external changes.
    @objc var changeCount: Int { get }

    // MARK: Management

    /// Clear all contents from the pasteboard
    @objc func clear()

    // MARK: Watcher

    /// The polling interval for the pasteboard watcher, in seconds. Defaults to 0.5.
    /// Changes take effect the next time a watcher is started (i.e. after removing and re-adding).
    @objc var watcherInterval: Double { get set }

    /// Add a watcher that is called whenever the pasteboard contents change.
    /// Multiple watchers may be registered; they are each called independently.
    /// Because macOS provides no pasteboard change notification API, this is implemented
    /// by polling `changeCount` at the interval specified by `watcherInterval`.
    /// - Parameter listener: A function called with one argument: the new `changeCount` integer
    @objc func addWatcher(_ listener: JSValue)

    /// Remove a previously registered pasteboard watcher
    /// - Parameter listener: The function previously passed to `addWatcher`
    @objc func removeWatcher(_ listener: JSValue)

    // NOTE: Private API consumed only by hs.pasteboard.js
    /// SKIP_DOCS
    @objc(_startWatcher::) func _startWatcher(_ interval: Double, _ callback: JSValue)
    /// SKIP_DOCS
    @objc func _stopWatcher()
    /// SKIP_DOCS
    @objc var _watcherEmitter: JSValue? { get set }
}

// MARK: - Implementation

@_documentation(visibility: private)
@MainActor
@objc class HSPasteboardModule: NSObject, HSModuleAPI, HSPasteboardModuleAPI {
    var name = "hs.pasteboard"

    @objc var watcherInterval: Double = 0.5
    @objc var _watcherEmitter: JSValue? = nil

    private var watcherTimer: Timer? = nil
    private var watcherCallback: JSValue? = nil
    private var lastChangeCount: Int = 0

    override required init() { super.init() }

    func shutdown() {
        _stopWatcher()
    }

    isolated deinit {
        print("Deinit of \(name)")
        shutdown()
    }

    // MARK: - Reading

    @objc func readString() -> String? {
        NSPasteboard.general.string(forType: .string)
    }

    @objc func readHTML() -> String? {
        NSPasteboard.general.string(forType: .html)
    }

    @objc func readRTF() -> String? {
        NSPasteboard.general.string(forType: .rtf)
    }

    @objc func readURL() -> String? {
        guard let urls = NSPasteboard.general.readObjects(forClasses: [NSURL.self], options: nil) as? [URL],
              let url = urls.first else { return nil }
        return url.absoluteString
    }

    @objc func readImage() -> HSImage? {
        guard let images = NSPasteboard.general.readObjects(forClasses: [NSImage.self], options: nil) as? [NSImage],
              let image = images.first else { return nil }
        return image.toBridge()
    }

    @objc(readData:) func readData(_ uti: String) -> String? {
        guard let data = NSPasteboard.general.data(forType: NSPasteboard.PasteboardType(uti)) else { return nil }
        return data.base64EncodedString()
    }

    // MARK: - Writing

    @objc func writeString(_ str: String) -> Bool {
        NSPasteboard.general.clearContents()
        return NSPasteboard.general.setString(str, forType: .string)
    }

    @objc func writeHTML(_ html: String) -> Bool {
        NSPasteboard.general.clearContents()
        return NSPasteboard.general.setString(html, forType: .html)
    }

    @objc func writeRTF(_ rtf: String) -> Bool {
        NSPasteboard.general.clearContents()
        return NSPasteboard.general.setString(rtf, forType: .rtf)
    }

    @objc func writeURL(_ urlString: String) -> Bool {
        guard let url = URL(string: urlString), url.scheme != nil else {
            AKError("hs.pasteboard.writeURL(): Invalid URL: \(urlString)")
            return false
        }
        NSPasteboard.general.clearContents()
        return NSPasteboard.general.writeObjects([url as NSURL])
    }

    @objc func writeImage(_ image: HSImage) -> Bool {
        NSPasteboard.general.clearContents()
        return NSPasteboard.general.writeObjects([image.image])
    }

    @objc(writeData::) func writeData(_ base64: String, _ uti: String) -> Bool {
        guard let data = Data(base64Encoded: base64) else {
            AKError("hs.pasteboard.writeData(): Invalid base64 string")
            return false
        }
        NSPasteboard.general.clearContents()
        return NSPasteboard.general.setData(data, forType: NSPasteboard.PasteboardType(uti))
    }

    @objc func writeObjects(_ representations: JSValue) -> Bool {
        guard representations.isObject, let rawDict = representations.toDictionary() else {
            AKError("hs.pasteboard.writeObjects(): Expected a JavaScript object with UTI string keys and string values")
            return false
        }

        let item = NSPasteboardItem()
        var wroteAtLeastOne = false

        for (key, value) in rawDict {
            guard let uti = key as? String, let str = value as? String else { continue }
            item.setString(str, forType: NSPasteboard.PasteboardType(uti))
            wroteAtLeastOne = true
        }

        guard wroteAtLeastOne else {
            AKWarning("hs.pasteboard.writeObjects(): No valid UTI/string pairs found in the provided object")
            return false
        }

        NSPasteboard.general.clearContents()
        return NSPasteboard.general.writeObjects([item])
    }

    // MARK: - Introspection

    @objc func types() -> [String] {
        NSPasteboard.general.types?.map(\.rawValue) ?? []
    }

    @objc func hasType(_ uti: String) -> Bool {
        NSPasteboard.general.availableType(from: [NSPasteboard.PasteboardType(uti)]) != nil
    }

    @objc var changeCount: Int {
        NSPasteboard.general.changeCount
    }

    // MARK: - Management

    @objc func clear() {
        NSPasteboard.general.clearContents()
    }

    // MARK: - Watcher

    @objc func addWatcher(_ listener: JSValue) {
        _watcherEmitter?.invokeMethod("on", withArguments: [listener])
    }

    @objc func removeWatcher(_ listener: JSValue) {
        _watcherEmitter?.invokeMethod("removeListener", withArguments: [listener])
    }

    @objc(_startWatcher::) func _startWatcher(_ interval: Double, _ callback: JSValue) {
        _stopWatcher()
        lastChangeCount = NSPasteboard.general.changeCount
        watcherCallback = callback
        watcherTimer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated {
                guard let self else { return }
                let current = NSPasteboard.general.changeCount
                if current != self.lastChangeCount {
                    self.lastChangeCount = current
                    self.watcherCallback?.call(withArguments: [current])
                }
            }
        }
        AKTrace("hs.pasteboard._startWatcher(): Polling started at \(interval)s interval")
    }

    @objc func _stopWatcher() {
        guard watcherTimer != nil else { return }
        watcherTimer?.invalidate()
        watcherTimer = nil
        watcherCallback = nil
        AKTrace("hs.pasteboard._stopWatcher(): Polling stopped")
    }
}
